apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm
  labels:
    app: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpm
  template:
    metadata:
      annotations:
      labels:
        app: fpm
    spec:
      containers:
        - name: fpm
          image: adilmektoub06/kubi_fpm
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
