apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
