apiVersion: v1
kind: Service
metadata:
  name: service-front-loadbalancer
  labels:
    app: service-front-loadbalancer

spec:
  type: LoadBalancer
  ports:
  - name: front-service
    port: 80
    protocol: TCP
  selector:
    app: front