version: '3'

networks:
  app:
    driver: bridge

services:
  php:
    build:
      context: ./back/
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./back:/back
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back:/back
    networks:
      - app

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports: 
      - "33601:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    env_file:
      - ./back/.env
    environment:
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: $${MYSQL_USER}
      MYSQL_PASSWORD: $${MYSQL_PASSWORD}
      # ces variable m'empeche de me connecter a la base de donnee
      DB_CONNECTION: $${DB_CONNECTION}
      DB_DATABASE: $${DB_DATABASE}
      DB_USERNAME: $${DB_USERNAME}
      DB_PASSWORD: $${DB_PASSWORD}
    networks:
      - app