version: '3.9'

networks:
  laravel:
    driver: bridge

services:
# last created is front
  front:
    container_name: front
    build: ./front
    ports:
      - 80:80
    networks:
      - laravel

  fpm:
    container_name: fpm
    env_file:
      - "./.env"
    build:
      context: ./
      dockerfile: docker/fpm.dockerfile
    ports:
      - 8000:8000
    links:
      - db
    networks:
      - laravel

  db:
    container_name: db
    image: mysql:5.7
    env_file:
      - "./.env"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: $${MYSQL_USER}
      MYSQL_PASSWORD: $${MYSQL_PASSWORD}
      MYSQL_DATABASE: $${MYSQL_DATABASE}
    networks:
      - laravel
