version: '3'

services:
# last created is front
  front:
    container_name: front
    build: ./front
    ports:
      - 80:80
    depends_on:
      - fpm
    networks:
      - front
  fpm:
    container_name: fpm
    build:
      context: ./
      dockerfile: docker/fpm.dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
    networks:
      - back
      - front

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    env_file:
      - "./.env"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dblaravel
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '3306:3306'
    networks:
      - back

  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - front
      - back

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitMQ.dockerfile
    env_file:
      - "./.env"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - messaging
      - back

networks:
  front:
    driver: bridge
  back:
  messaging:
      driver: bridge
volumes:
  mysql_data: { driver: local }
