version: '3.9'

networks:
  laravel:

services:
# last created is front
  front:
    container_name: front
    build: ./front
    ports:
      - 80:80
    networks:
      - laravel
    depends_on:
      - nginx
      - mysql
      - fpm

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8098:80
    volumes:
      - ./:/var/www/html
    links:
      - fpm
    networks:
      - laravel

  fpm:
    build:
      context: .
      dockerfile: docker/fpm.dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - db
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bdlaravel
    networks:
      - laravel
